### PR TITLE
QA/QC

### PR DESCRIPTION
**Pull request by MRossol**
Add QA/QC module with:
Summarize:
- Class to summarize datasets using pandas.describe
SummaryPlots:
- Plot scatter, supply_curve, and dist plots of summary data

### CODE REVIEW

**Comment by MRossol** [comment]
@grantbuster Things to think about:
1) What do we want to be the default plots: 
- .pngs from plotting
- .html from plotly
2) Do we want to make classes for QA on each module? If so maybe qa_qc becomes a sub_package instead of a utility?
3) Besides summary tables and plots what other QA should we do?

**Comment by grantbuster** [comment]
@MRossol, looks good but what about 1) summary statistics for csv files (supply curve mean and total capacities, lcoe, etc...) 2) integration into pipeline?

**Comment by MRossol** [comment]
@grantbuster  for SC summary, should I compute the mean, stdev, median, min, max, and sum for all numerical columns? Or a subset of columns? 

I'm working on a QA/QC CLI, but would love your thoughts on pipeline integration...

**Comment by grantbuster** [comment]
Would be really quick to do all columns right? Any reasons why we wouldn't want to do all numeric columns?

Want to set up a call on Monday about pipeline integration?

**Comment by MRossol** [comment]
Agreed and sure!

**Comment by MRossol** [comment]
@grantbuster QA/QC CLI is updated with config option. I'll start working on a config example but would love your help integrating with the pipeline and updating the pipeline example

**Comment by grantbuster** [comment]
@MRossol, sure thing! Can you send me the config example when its done? Or just add it to the current pipeline example? I'll try and get to that this week if thats okay.

**Comment by MRossol** [comment]
@grantbuster qa_qc config example added to the pipeline example folder

**Pull request merged**
