### PR TITLE
Gb/sam tz input

### PR DESCRIPTION
**Pull request by grantbuster**
Minor feature to better allow for timezone and elevation to be input via the reV gen/econ site_data input. Useful feature when we're dealing with forecast or other misc datasets with weird meta data.

### CODE REVIEW

**Review by MRossol — APPROVED** [review]
Looks good, can we add a test?

**Comment by grantbuster** [comment]
Yes can add test... any ideas on what a good test would be?

**Comment by MRossol** [comment]
I think a baseline forecast test that uses the gid_map and site_data with tz and elevation data would be great, both from an example standpoint and just to make sure both functions are passing data through properly

**Comment by grantbuster** [comment]
Okay added kind of an integrated gen forecast test that we can pile our misc forecast features into. I think this works!

**Pull request merged**
